version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: dev-php
    volumes:
      - ./:/var/www/html:cached
    ports:
      - '80:80'
    depends_on:
      - db

  db:
    image: mariadb:10.7
    container_name: dev-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dev-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - '8081:80'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dev-frontend
    volumes:
      - ./frontend:/app:cached
    ports:
      - '3000:3000'
    command: npm run dev
    depends_on:
      - php

volumes:
  db_data:
