nav:
  - Vue d'ensemble: index.md
  - Base de données: Database.md
  - Configuration: config.md
  - Scripts SQL:
    - Création base: database_creation.md
    - Données de test: gen_test_data_v1.md
  - Traits: Traits/
  - Types: Types/
  - Rapport: COMPLETENESS-REPORT.md
